{
 "title": "Flask App Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flask HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flask_http_request_total) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Flask HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_bucket{le=\"0.1\"}",
     "legendFormat": "0.1s"
    },
    {
     "expr": "flask_http_request_duration_seconds_bucket{le=\"0.5\"}",
     "legendFormat": "0.5s"
    },
    {
     "expr": "flask_http_request_duration_seconds_bucket{le=\"1.0\"}",
     "legendFormat": "1.0s"
    }
   ]
  },
  {
   "title": "Flask GC Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "{{generation}}" }
   ]
  },
  {
   "title": "Flask Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual Memory" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident Memory" }
   ]
  }
 ]
}