kube-prometheus-stack:
  prometheus:
    replicas: 1
    service:
      type: NodePort
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false          

  grafana:
    replicas: 1
    service:
      type: NodePort
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

  alertmanager:
    replicas: 1
    alertmanagerSpec:
      service:
        type: NodePort
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

  kube-state-metrics:
    enabled: false

  nodeExporter:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  coreDns:
    enabled: false
