apiVersion: v1
kind: Service
metadata:
  name: deployment-validation-webhook
  namespace: deployment-validate
spec:
  selector:
    app: deployment-validation-webhook
  ports:
    - protocol: TCP
      port: 4430
      targetPort: 4430
