apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-service-monitor
  labels:
    release: prometheus-minimal  
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: flask-app
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
      scheme: http


