apiVersion: v1
kind: Pod
metadata:
  name: ansible
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker  
  - name: ansible
    image: canerturkaslan/ansible-alpine:0.1
    command:
    - /bin/cat
    tty: true    
    volumeMounts:
    - name: kubeconfig-volume
      mountPath: /root/.kube/config
      subPath: config
  volumes:
  - name: kubeconfig-volume
    secret:
      secretName: kubeconfig-secret
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
      items:
        - key: .dockerconfigjson
          path: config.json        
