- name: Deploy Kubernetes Manifests
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    kube_namespace: default
    deployment_name: flask-app
    service_name: flask-app-service
    manifest_path: manifest

  tasks:
    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: "{{ kube_namespace }}"
        state: present

    - name: Create Kubernetes YAML from Jinja2 template
      template:
        src: "deployment.j2"
        dest: "{{ manifest_path }}/deployment.yaml"


    - name: Apply Deployment
      k8s:
        dest: "{{ manifest_path }}/deployment.yaml"
        namespace: "{{ kube_namespace }}"


    - name: Apply HPA
      k8s:
        src: "{{ manifest_path }}/hpa.yaml"
        namespace: "{{ kube_namespace }}"

    - name: Apply Service
      k8s:
        src: "{{ manifest_path }}/service.yaml"
        namespace: "{{ kube_namespace }}"


    - name: Apply Ingress
      k8s:
        src: "{{ manifest_path }}/ingress.yaml"
        namespace: "{{ kube_namespace }}"
   

    - name: Apply Service Monitor
      k8s:
        src: "{{ manifest_path }}/service_monitor.yaml"
        namespace: "{{ kube_namespace }}"
           

