pipeline {
  agent {
    kubernetes {
      yamlFile './app/builder.yaml'
    }
  }
  
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    
    stage('Build and Push') {
  
    steps {
      container(name: 'kaniko') {
        // Kaniko ile Docker imajını build ve push işlemi
        script {
          sh '''

          /kaniko/executor --dockerfile `pwd`/app/Dockerfile \
                           --context `pwd` \
                           --destination=canerturkaslan/flask-app:0.${BUILD_NUMBER}
          '''
        }
      }
    }
  }    
 

  }
}

