---
elasticsearchHosts: "https://security-master:9200"
elasticsearchCertificateSecret: elastic-certificate-pem
elasticsearchCertificateAuthoritiesFile: elastic-certificate.pem
elasticsearchCredentialSecret: security-master-credentials

extraEnvs:
  - name: "KIBANA_ENCRYPTION_KEY"
    valueFrom:
      secretKeyRef:
        name: kibana
        key: encryptionkey

kibanaConfig:
  kibana.yml: |
    server.ssl.certificate: /usr/share/kibana/config/certs/elastic-certificate.pem
    server.ssl.enabled: true
    server.ssl.key: /usr/share/kibana/config/certs/elastic-certificate.pem
    xpack.security.encryptionKey: qNh4NnZRPL3W3oZmLc3Rh0vsNR0x94cmcnMzg3YICjXDIJ0cwu

protocol: https

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 760Mi

## Authentication
env:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "caner12345"

## Service type
service:
  type: NodePort


