apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool"
spec:
  blocks:
  - start: "192.168.123.75"
    stop: "192.168.123.80"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2policy
spec:
  serviceSelector:
    matchLabels:
      expose: ingress
  loadBalancerIPs: true
  externalIPs: true
  interfaces:
    - eth1

